react:
    build: .
    ports:
        - 9002
        - 3000
    command: start  
    environment:
        VIRTUAL_HOST: reactloki.test
        VIRTUAL_PORT: 3000
    volumes:
        - .:/project
    links:
        - redis
    
redis:
    image: redis:3.2.8-alpine

storybook:
    build: ./docker/front
    ports:
        - 9001
        - 9009
    environment:
        VIRTUAL_HOST: styleguide.reactloki.test
        VIRTUAL_PORT: 9009
    command: storybook
    volumes:    
        - .:/project

loki:
    build: ./docker/front
    command: test -- --host styleguide.reactloki.test/ 
    links:
         - storybook
    environment:
        VIRTUAL_HOST: styleguide.reacloki.test
        VIRTUAL_PORT: 9009
    entrypoint: yarn loki
    volumes:
        - .:/project
        - ~/.yarn-cache:/root/.yarn-cache
        - ~/.yarn/cache:/root/yarn/cache
        - /var/run/docker.sock:/var/run/docker.sock:ro
